[package]
org = "digitalpaymentshub"
name = "drivers.lankapay"
version = "0.0.1"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "digitalpaymentshub"
name = "drivers.util"
version = "0.0.10"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "financial.iso8583"
version = "0.1.2"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "financial.iso20022"
version = "0.0.4"
repository = "local"
